# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  #imageName: '$(imagename)'
  imageTag: '$(Build.BuildId)'

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        docker build -t $(imagename):$(imageTag) .
        echo $(imageTag)
        
        TAR_FILE=$(Build.ArtifactStagingDirectory)/$(imagename)-$(imageTag).tar
            echo "Saving Docker image to tarball $TAR_FILE"
            docker save -o $TAR_FILE $(imagename):$(imageTag)
    displayName: 'Build Docker image'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Docker image as artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'  
      ArtifactName: 'docker-image'
      publishLocation: 'Container'



